var Language_General = {
    "es-ES": {
        Error: "ERROR",
        Please_Report_To_Help_Desk: "Se produjo un error al realizar la peticiton el servidor , por favor informe a Mesa de Ayuda",
        Session_Expired_Message: "La session ha expirado, por favor inicie session nuevamente",
        Select_Option: "Seleccione una opcion",
        Notification: "NOTIFICACION",
        NO_FOUND_RECORDS_: "No se encontraron datos",
        SESSION_EXPIRED_: "La sesion del usuario a terminado",
        teamSystem: "Favor de reportar al departamento de sistemas.",
        PROJECT_NO_SETTED_: "Seleccione un proyecto antes de continuar.",
        LOADING: "Procesando...",
        SELECT: "Seleccione",
        lbl_btnSave: "Guardar",
        lbl_btnSearch: "Filtrar",
        lbl_btnNew: "Nuevo",
        lbl_btnAuth: "Autorizar",
        lbl_btnDownload: "Descargar",
        lbl_btnUpload: "Cargar",
        lbl_btnClear: "Limpiar",
        lbl_btnCacel: "Cancelar",
        lbl_btnExport: "Exportar",
        lbl_btnAdd: "Agregar",
        lbl_success: "Exito",
        lbl_warning: "Advertencia",
        lbl_close : "Cerrar",
        //ACCO-Validator
        alias: "campo",
        fieldRequired: "La informacion de {0} es requerida.",
        fieldEmailWrong: "La informacion de {0} no es una direccion de correo electronico valida.",
        fieldNumericFail: "La informacion de {0} debe de ser un valor numerico.",
        fieldNumericFail_upZero: "La informacion de {0} debe de ser un valor numerico mayor a cero.",
        fieldNumericFail_downZero: "La informacion de {0} debe de ser un valor numerico menor a cero.",
        fieldIntegerFail: "La informacion de {0} debe de ser un numero entero.",
        fieldIntegerFail_upZero: "La informacion de {0} debe de ser un numero entero mayor a cero.",
        fieldIntegerFail_downZero: "La informacion de {0} debe de ser un numero entero menor a cero.",
        fieldPasswordWrong: "La informacion de {0} debe contener al menos una letra minúscula, una letra mayúscula, un caracter especial <b>(</b>#$@!%&-_|\\()+*={}[]^.<b>)</b>  y un digito, con una longitud minima de 8 caracteres.",
        fieldDateWrong: "El formato de {0} es incorrecto, necesita ser {1}.",
        //calendar helpers
        monthsName: [
            "Enero",
            "Febrero",
            "Marzo",
            "Abril",
            "Mayo",
            "Junio",
            "Julio",
            "Agosto",
            "Septiembre",
            "Octubre",
            "Noviembre",
            "Diciembre"
        ],
        daysName: [
            "Domingo",
            "Lunes",
            "Martes",
            "Miercoles",
            "Jueves",
            "Viernes",
            "Sabado"
        ],
        monthsNameShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dec'],
        daysNameShort: ['Dom','Lun','Mar','Mie','Jue','Vie','Sab']
    },
    "en-US": {
        Error: "ERROR",
        Please_Report_To_Help_Desk: "An error occurred while performing the request to the server , please report to Help desk",
        Session_Expired_Message: "Session expired, Please start session again",
        Select_Option: "Select Option",
        Notification: "NOTIFICATION",
        NO_FOUND_RECORDS_: "No Data Found", 
        SESSION_EXPIRED_: "The session is over",
        teamSystem: "Unexpected error, please report to Help Desk for assistance.",
        PROJECT_NO_SETTED_: "Select a project before continued.",
        LOADING: "Processing...",
        SELECT: "Select",
        lbl_btnSave: "Save",
        lbl_btnSearch: "Search",
        lbl_btnNew: "New",
        lbl_btnAuth: "Authorize",
        lbl_btnDownload: "Download",
        lbl_btnUpload: "Upload",
        lbl_btnClear: "Clear",
        lbl_btnCacel: "Cancel",
        lbl_btnExport: "Export",
        lbl_btnAdd: "Add",
        lbl_success: "Success",
        lbl_warning: "Warning",
        lbl_close : "Close",
        //ACCO-Validator
        alias: "field",
        fieldRequired: "The information about {0} is required.",
        fieldEmailWrong: "The information about {0} is not a valid Email address.",
        fieldNumericFail: "Information {0} must be a numeric value.",
        fieldNumericFail_upZero: "Information {0} must be a numeric value greater than zero.",
        fieldNumericFail_downZero: "Information {0} must be a numeric value less than zero.",
        fieldIntegerFail: "Information {0} must be a integer number value.",
        fieldIntegerFail_upZero: "Information {0} must be a integer number greater than zero.",
        fieldIntegerFail_downZero: "Information {0} must be a integer number less than zero.",
        fieldPasswordWrong: "The information about {0} must contain at least one lowercase letter, a capital letter, a special character <b>(</b>#$@!%&-_|\\()+*={}[]^.<b>)</b> and a digit, with a minimum length of 8 characters.",
        fieldDateWrong: "The format of {0} it is wrong, needs to be {1}.",
        //calendar helpers
        monthsName: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ],
        daysName: [
            "Sunday",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
        ],
        monthsNameShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
        daysNameShort: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
    },
    "ar-AR": {
        "Error": "خطأ",
        "Please_Report_To_Help_Desk": "حدث خطأ أثناء تنفيذ طلب إلى الخادم، يرجى إبلاغ مكتب المساعدة",
        "Session_Expired_Message": "الدورة منتهية الصلاحية، الرجاء بدء جلسة ثانية",
        "Select_Option": "حدد الخيار",
        "Notification": "الإخطار",
        "NO_FOUND_RECORDS_": "لاتوجد بيانات",
        "SESSION_EXPIRED_": "انتهت الدورة",
        "teamSystem": "يرجى إبلاغ نظم فريق.",
        "PROJECT_NO_SETTED_": "حدد مشروع استمر من قبل.",
        "LOADING": "معالجة...",
        "SELECT": "اختار",
        "lbl_btnSave": "حفظ",
        "lbl_btnSearch": "بحث",
        "lbl_btnNew": "جديد",
        "lbl_btnAuth": "يأذن",
        "lbl_btnDownload": "تحميل",
        "lbl_btnUpload": "تحميل",
        "lbl_btnClear": "واضح",
        "lbl_btnCacel": "إلغاء",
        "lbl_btnExport": "تصدير",
        "lbl_btnAdd": "إضافة",
        "lbl_success": "نجاح",
        "lbl_warning": "تحذير",
        "lbl_close" : "قريب",
        "alias": "حقل",
        "fieldRequired": "مطلوب معلومات عن {0}.",
        "fieldEmailWrong": "المعلومات حول {0} انها ليست عنوان بريد إلكتروني صالح.",
        "fieldNumericFail": "يجب أن تكون المعلومات {0} قيمة رقمية.",
        "fieldNumericFail_upZero": "يجب أن تكون المعلومات {0} قيمة رقمية أكبر من الصفر.",
        "fieldNumericFail_downZero": "يجب أن تكون المعلومات {0} قيمة رقمية أقل من الصفر.",
        "fieldIntegerFail": "معلومات {0} يجب أن تكون قيمة عدد صحيح.",
        "fieldIntegerFail_upZero": "معلومات يجب أن يكون عدد صحيح أكبر من الصفر {0}.",
        "fieldIntegerFail_downZero": "معلومات يجب أن يكون {0} عدد صحيح أقل من الصفر.",
        "fieldPasswordWrong": "المعلومات حول {0} يجب أن يحتوي على حرف واحد على الأقل صغيرة، بريد إلكتروني رأس المال، وذات طابع خاص <b>(</b> # $ @٪ & -_ |! \\ () + * = {} [] ^. <b>) </b> وأرقام، مع الحد الأدنى للطول من 8 أحرف.",
        "fieldDateWrong": "شكل {0} من الخطأ، يجب أن يكون {1}.",
        //calendar helpers
        monthsName: [
            "يناير",
            "فبراير",
            "مارس",
            "أبريل",
            "مايو",
            "يونيو",
            "يوليو",
            "أغسطس",
            "سبتمبر",
            "أكتوبر",
            "نوفمبر",
            "ديسمبر"
        ],
        daysName: [
            "الأحد",
            "الإثنين",
            "الثلاثاء",
            "الأربعاء",
            "الخميس",
            "الجمعة",
            "يوم السبت"
        ],
        monthsNameShort: [
            "يناير",
            "فبراير",
            "مارس",
            "أبريل",
            "مايو",
            "يونيو",
            "يوليو",
            "أغسطس",
            "سبتمبر",
            "أكتوبر",
            "نوفمبر",
            "ديسمبر"
        ],
        daysNameShort: [
            "الأحد",
            "الإثنين",
            "الثلاثاء",
            "الأربعاء",
            "الخميس",
            "الجمعة",
            "يوم السبت"
        ]
    }
    
};

var LanguageDataTables = {
    "en-US": {
        "sEmptyTable": "No data available in table",
        "sInfo": "Showing _START_ to _END_ of _TOTAL_ entries",
        "sInfoEmpty": "Showing 0 to 0 of 0 entries",
        "sInfoFiltered": "(filtered from _MAX_ total entries)",
        "sInfoPostFix": "",
        "sInfoThousands": ",",
        "sLengthMenu": "Show _MENU_ entries",
        "sLoadingRecords": "Loading...",
        "sProcessing": "Processing...",
        "sSearch": "Search: ",
        "sZeroRecords": "No matching records found",
        "oPaginate": {
            "sFirst": "First",
            "sLast": "Last",
            "sNext": "Next",
            "sPrevious": "Previous"
        },
        "oAria": {
            "sSortAscending": ": activate to sort column ascending",
            "sSortDescending": ": activate to sort column descending"
        }
    },
    "es-ES": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar: ",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "Primero",
            "sLast": "Último",
            "sNext": "Siguiente",
            "sPrevious": "Anterior"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
    },
    "ar-SA": {
        "sEmptyTable": "لا توجد بيانات في الجدول",
        "sInfo": "عرض _START_ إلى _END_ من إدخالات _TOTAL_",
        "sInfoEmpty": "عرض 0-0 من 0 مقالات",
        "sInfoFiltered": "(تصفيتها من مجموع المقالات _MAX_)",
        "sInfoPostFix": "",
        "sInfoThousands": "،",
        "sLengthMenu": "تظهر إدخالات _MENU_",
        "sLoadingRecords": "جار التحميل...",
        "sProcessing": "معالجة...",
        "sSearch": "بحث:",
        "sZeroRecords": "لا توجد سجلات مطابقة",
        "oPaginate": {
            "sFirst": "الأول",
            "sLast": "آخر",
            "sNext": "التالى",
            "sPrevious": "سابق"
        },
        "oAria": {
            "sSortAscending": ": تفعيل لفرز العمود تصاعدي",
            "sSortDescending": ": تفعيل لفرز العمود الهابطة"
        }
    }
} 